### ISSUE TITLE
Unable to install pyccuracy-1.2.4 to a clean (virtual) environment

### ISSUE THREAD

**Issue by tomikall** [heynemann/pyccuracy#48]
Installation of pyccuracy-1.2.4 fails when `setup.py` is imported.  This happens because of `from pyccuracy import Version` on line 16; while pulling in `Version` from `pyccuracy/__init__.py`, imports for lxml and selenium are encountered and `ImportError` is raised.

This fails:

```
$ virtualenv --no-site-packages pyccuracy-test
...
~/tmp$ source pyccuracy-test/bin/activate
(pyccuracy-test)~/tmp$ easy_install pyccuracy==1.2.4
...
Traceback (most recent call last):
  ...
  File "/tmp/easy_install-buhxET/Pyccuracy-1.2.4/pyccuracy/page.py", line 21, in <module>
ImportError: No module named lxml
```

This succeeds:

```
(pyccuracy-test)~/tmp$ easy_install lxml
...
(pyccuracy-test)~/tmp$ easy_install selenium
...
(pyccuracy-test)~/tmp$ easy_install pyccuracy==1.2.4
...
Processing dependencies for pyccuracy==1.2.4
Finished processing dependencies for pyccuracy==1.2.4
```

Also, lxml is not listed in `install_requires` in `setup.py` so easy_install would be unaware of the dependency even if the above import issue was fixed.

**Comment by heynemann** [comment]
I'll fix that, but you appear to have a good knowledge into how to fix it. Do you mind providing a patch? If you can't I'll get to it asap!

Thanks!

**Comment by heynemann** [comment]
I just recently installed Pyccuracy to a virtualenv without any issues. Can you provide more info on the error? Or does it still occur with the latest Pyccuracy release?
Cheers,
Bernardo Heynemann

**Comment by tomikall** [comment]
Yes, it still occurs with Pyccuracy 1.2.19. I assume that the reason why it does not occur for you is that you have both lxml and selenium installed into the site-packages of your Python interpeter (or Python has some other way of accessing those at the time "easy_install pyccuracy" is run, e.g. via a .pth file).

On my machine, I have a clean Python 2.6 installation and I get the same errors listed in the original issue. You can reproduce this if you create the virtualenv with the `--no-site-packages` switch AND make sure lxml and selenium are not available before installing pyccuracy. In your new, activated virtualenv, run:

```
$ python -c "import lxml"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lxml
$ python -c "import selenium"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named selenium
```

If you don't get those ImportErrors, you already have the libs in place and easy_install will happily fetch and install pyccuracy for you. These libs could be installed by your Linux distro's package manager, for example.

The rest of us still have this problem though, and our automatic deployment scripts will need to make sure both lxml and selenium are installed _before_ trying to install pyccuracy. Selenium is listed as a dependency in `install_requires` of setup.py but the ImportErrors are raised when "from pyccuracy import Version" is executed (line 16) so `install_requires` is never even seen by easy_install.

**Comment by heynemann** [comment]
I'll definitely fix that in this release! Thanks :)

**Comment by heynemann** [comment]
Should be fixed in release 1.2.26. The dependency on lxml is SOFT now, meaning you don't NEED to have LXML (even though you'll miss some feats). Dependency on selenium is still there.

**Comment by tomikall** [comment]
I sound like a broken record already but anyway... The same issue still exists, i.e. when installing pyccuracy (with either easy_install or pip), there is a _install_time_ dependency on selenium. I understand this is not the most pressing problem for people but anyway, you could work your way around it by changing your imports.

This is what I now get when installing to a new and clean virtualenv with pip:

```
$ pip install pyccuracy
Downloading/unpacking pyccuracy
  Downloading Pyccuracy-1.2.26.tar.gz (52Kb): 52Kb downloaded
  Storing download in cache at ./.pip/download_cache/http%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2FP%2FPyccuracy%2FPyccuracy-1.2.26.tar.gz
  Running setup.py egg_info for package pyccuracy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/tomikall/.virtualenvs/pyccuracy-test/build/pyccuracy/setup.py", line 16, in <module>
        from pyccuracy import Version
      File "pyccuracy/__init__.py", line 23, in <module>
        from pyccuracy.drivers.core import *
      File "pyccuracy/drivers/core/selenium_driver.py", line 22, in <module>
        from selenium import *
    ImportError: No module named selenium
```

Selenium is needed when pyccuracy is executed but it should not be needed during installation. Here is a quick-and-dirty fix to setup.py to get around the issue:

```
#from pyccuracy import Version
Version = re.search(r"Version = \"(.*?)\"", open("pyccuracy/__init__.py").read()).groups()[0]
```

So, instead of importing the pyccuracy package (and as a side-effect, pulling in many other pyccyracy modules including "selenium_driver.py" that results in ImportError because selenium is not there yet) we parse the version information from the "raw" file. This might not be The Right Way to do it but it does show you what the issue is and how to get around it. After this small "fix", pyccuracy installs just fine with both easy_install and pip, AND selenium is automatically downloaded and installed as well as a dependency.

**Comment by heynemann** [comment]
Fixed once more in release 1.2.27. Please try it.

**Comment by tomikall** [comment]
Installation of 1.2.28 (using Github hosted Pyccuracy-1.2.28.tar.gz) was successful with both easy_install and pip. Now it only needs to be made available through PyPi so that others will find it as well.

Thank you for all the effort you put into resolving this!
